Added messages controller
Scopee/JokesMessenger pull request #3
Opened 2021-10-14 05:10 UTC by Jaz7Mutant

2021-10-15 10:17 UTC, Scopee requested changes

2021-10-15 10:17 UTC, Scopee commented on src/main/java/ru/pinguin/jokesmessenger/messages/SendMessageRequest.java
> +    private UUID from;
Давай примеры и описание сразу добавим

2021-10-15 10:17 UTC, Scopee commented on src/main/java/ru/pinguin/jokesmessenger/messages/MessagesApi.java
> +    @GetMapping("/{userId}")
Может requestParam? Чтобы как везде было
Тем более у тебя пересечется этот метод + метод ниже и будут ошибки

2021-10-15 10:17 UTC, Scopee commented on src/main/java/ru/pinguin/jokesmessenger/messages/GetMessageRequest.java
> +    private UUID id;
Аналогично пример

2021-10-15 10:17 UTC, Scopee commented on src/main/java/ru/pinguin/jokesmessenger/messages/MessagesApi.java
> +    List<GetMessageRequest> getMessages(@PathVariable UUID userId, @RequestParam Integer offset, @RequestParam Integer limit);
Ну и можно еще примеры для параметров запроса

2021-10-20 16:14 UTC, Jaz7Mutant commented on src/main/java/ru/pinguin/jokesmessenger/messages/MessagesApi.java
> +    List<GetMessageRequest> getMessages(@PathVariable UUID userId, @RequestParam Integer offset, @RequestParam Integer limit);
можно ненадо?

2021-10-20 16:16 UTC, Scopee requested changes

2021-10-20 16:16 UTC, Scopee commented on src/main/java/ru/pinguin/jokesmessenger/messages/MessagesApi.java
>      @GetMapping
Почему get?

2021-10-20 16:49 UTC, Scopee approved these changes

2021-10-20 16:49 UTC, merged